### ISSUE TITLE
Unable to run the SRSLTE enodeb

### ISSUE THREAD

**Issue by Manash-UAS** [Gradiant/openverso-images#18]
Hello Team,

I am trying to run the srslte.yaml and create enodeb and ue containers.
I found it in location https://github.com/Gradiant/openverso-images/tree/main/docs/open5gs-and-srslte

Following steps I followed:
1. Ran epc.yaml, which created all the open5gs containers but I am unable to login to the webUi the password is showing incorect. username: admin; password: 1423. But is is not working.
2. After running srslte.yaml, "ue" container is getting created but for "enb" is not. it is showing "Exit 1" when checking.

Not understanding why its happening. Can you please help.
![enb_exit](https://user-images.githubusercontent.com/56870468/157870745-e7d4aad7-98a9-46f2-bd1b-4680bc8c5b4a.png)

**Comment by cgiraldo** [comment]
Sorry but the `docs` tutorials are not updated.

I fix the open5gs-and-srslte in order to use the current open5gs (openverso/open5gs:2.4.4) and srs (openverso/srsran:21_10) images.

It should work now.

Please, reopen the issue if you find any problem.

**Comment by Manash-UAS** [comment]
Thank you for updating the tutorials.

Now able to login into the Open5gs webui.

But still not able to run the srsLTE containers. Now it is showing the error 'Exit 132'.

![exit132](https://user-images.githubusercontent.com/56870468/158353487-fceaec09-5147-42ce-9033-c537b9723f8a.png)

I am using Ubuntu 20.04 and running it in VirtualBox

**Comment by cgiraldo** [comment]
Please, update you local docker images and try again:

```
sudo docker-compose -f srslte.yaml pull
sudo docker-compose -f srslte.yaml up -d
```

**Comment by Manash-UAS** [comment]
I used the commands and it still giving the same error of "exit 132".

![exit132](https://user-images.githubusercontent.com/56870468/158382814-8eef769a-aa7c-4ae5-936d-e15e6e8d6f5e.png)

**Comment by Manash-UAS** [comment]
It is still not running. I have attached the log file.
![err132](https://user-images.githubusercontent.com/56870468/159484391-e5b00ed9-1312-4b5a-a002-4afefb90b61c.png)

[logs.txt](https://github.com/Gradiant/openverso-images/files/8324271/logs.txt)

**Comment by cgiraldo** [comment]
Hi. The log error states: 

`/entrypoint.sh: line 56:    36 Illegal instruction     (core dumped) /bin/srsenb enb.conf $@`

Are you running on a arm64 host?

Current openverso/srsran image is only built for x86 architecture.

**Comment by Manash-UAS** [comment]
I checked and it is running on x86-64.
I am using Ubuntu 18.04, running in VirtualBox.
![x86](https://user-images.githubusercontent.com/56870468/159582005-a2350358-713f-4ba4-b4b3-e5a0aced8885.png)

**Comment by cgiraldo** [comment]
That's the architecture of your VM, but what about the architecture of your host computer?

FYI our working environment is an Ubuntu 20.04 directly running on a x86_64 laptop (no VMs).

**Comment by Manash-UAS** [comment]
![image](https://user-images.githubusercontent.com/56870468/159914373-fcd07807-1eba-4c50-951b-dcb360689489.png)

My host computer is also amd64. I will try on Ubuntu 20.04 VM and see if it is working.

**Comment by Manash-UAS** [comment]
I tried on a different laptop to run the SRSRAN containers but still got the same error 'Exit 132'. I did not use VM this time.
Also I tried to build th
![dockerfile_error](https://user-images.githubusercontent.com/56870468/160372459-fe5b1544-2f59-47dd-815e-796e77df31ad.png)
e image using the Dockerfile present in "openverso-images/images/srsran". I got some error on step 6.

**Comment by aniklog** [comment]
I tried the same in the following environment.
OS: Ubuntu 21.10 in Base Machine (No VM)
But still the same error is generated
![DockerComposeError](https://user-images.githubusercontent.com/57104937/160377858-5a2c1938-0db1-4432-a940-cd0cfaa7e4ff.png)
.

**Comment by Manash-UAS** [comment]
I have tried on multiple PC with x86 architecture, still getting the same error. Can you please look into this.

**Comment by cgiraldo** [comment]
Hi,

I have finally been able to reproduce the error by using a AWS EC2 machine with ubuntu 20.04 on it.

It seems a problem related with some dependency between the dockerhub image and some property of the host running the image (cpu? kernel module? libraries?).

You can generate an image version that work for your environment if you build it from the Dockerfile. Just  run in `images/srsran` in your machine:
```
docker build -t openverso/srsran:21_10 --build-arg version=21_10 .
```

That will generate a local openverso/srsran:21_10 docker image that should run in your machine witout error. 

So try again the `docker-compose -f srslte.yaml up -d` after the build and let me know.

**Comment by cgiraldo** [comment]
I have updated the dockerhub image. It should now work in all hosts. Just upload your local image with:

```
docker pull openverso/srsran:21_10
```

prior to running the docker-compose instructions.

**Comment by Manash-UAS** [comment]
Thank you it is working now. 

While changing the default route I am getting this error.
![default route](https://user-images.githubusercontent.com/56870468/162917316-73b5745b-9ce7-4e81-af10-4cd4f807636e.png)
